# Generated by Django 4.2.5 on 2024-06-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_user_alter_follow_user_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_followed',
            new_name='user_follower',
        ),
    ]
